### ISSUE TITLE
Allow to configure metrics endpoint

### ISSUE THREAD

**Issue by spigell** [andrewrothstein/ansible-etcd-cluster#12]
Hi. Is there any way to specify --listen-metrics-urls flag or ETCD_LISTEN_METRICS_URLS env var in this role without changing templates? It may be useful if a cluster configured with tls security, but prometheus/monitoring system want use plain http for metrics.

**Comment by andrewrothstein** [comment]
there’s the capability of inserting ur own random environment variables into the systemd service environment [here](https://github.com/andrewrothstein/ansible-etcd_cluster/blob/909187a7c583e6f7b32d25a0a172799f5364a08d/templates/etcd.conf.j2#L79). Open to a PR if u wanna generate it from other vars in the template.
