### ISSUE TITLE
More control over environment variables

### ISSUE THREAD

**Issue by neilschelly** [andrewrothstein/ansible-etcd-cluster#14]
I'd like to have more control over the environment variables that get written into /etc/etcd/etcd.conf here. In particular, I'm looking at the ETCD_AUTO_COMPACTION_MODE and ETCD_AUTO_COMPACTION_RETENTION options, but I can imagine others might be looking for more.

Would you be open to variable in Ansible that could just list a bunch of _other_ env vars to set in the ansible playbook so that it's easy for someone using the playbook to arbitrarily add new options to the config? I'll gladly submit a PR if you're interested.

**Comment by andrewrothstein** [comment]
absolutely open to such a PR!
