### ISSUE TITLE
Syntax error. In tasks/main.yml etcd_address_public, and etcd_address_cluster

### ISSUE THREAD

**Issue by clucia** [andrewrothstein/ansible-etcd-cluster#17]
The test 'is in' is used and (I believe) should be 'in'.

I'm totally new to the ansible community, so, if I've gone against any accepted 'etiquette', please excuse me.

The offending lines:

    etcd_address_public: '{{ ansible_fqdn if not etcd_use_ips | bool else ansible_default_ipv4.address if etcd_iface_public in [ "all", "default" ] else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_public]["ipv4"]["address"] }}'
    etcd_address_cluster: '{{ ansible_fqdn if not etcd_use_ips | bool else ansible_default_ipv4.address if etcd_iface_cluster in [ "all", "default" ] else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_cluster]["ipv4"]["address"] }}'

**Comment by andrewrothstein** [comment]
open to a tested PR to fix this.

**Comment by andrewrothstein** [comment]
Please try with v3.0.5 and confirmed I’ve addressed this. Thanks!
