### ISSUE TITLE
template error while templating string: no test named

### ISSUE THREAD

**Issue by rao76** [andrewrothstein/ansible-etcd-cluster#22]
I've been trying to deploy etcd-cluster on AlmaLinux-8 and encountered the below errors. Any help?

fatal: [10.208.2.35]: FAILED! => {"msg": "template error while templating string: no test named 'in'. String: {{ ansible_fqdn if not etcd_use_ips | bool else ansible_default_ipv4.address if etcd_iface_cluster is in [ \"all\", \"default\" ] else hostvars[inventory_hostname][\"ansible_\" ~ etcd_iface_cluster][\"ipv4\"][\"address\"] }}"}

**Comment by andrewrothstein** [comment]
I think I fixed this in v3.0.5. Can u try again and lmk?
