### ISSUE TITLE
Versions since v2.0.0 are absent on Galaxy 

### ISSUE THREAD

**Issue by prep0sterous** [andrewrothstein/ansible-etcd-cluster#26]
https://galaxy.ansible.com/ui/standalone/roles/andrewrothstein/etcd-cluster/ has v2.0.0 as the last version

**Comment by andrewrothstein** [comment]
https://galaxy.ansible.com/ui/standalone/roles/andrewrothstein/etcd_cluster/versions/ shows all versions.
