### ISSUE TITLE
Make certificate authentication option configurable

### ISSUE THREAD

**Issue by jk-mtnv** [andrewrothstein/ansible-etcd-cluster#37]
Dear maintainers,

I have faced a problem with disabling the certificate authentication while still keeping the security enabled.

The certificate authentication method takes precedence over the user/password method. However, it does not work with the etcd gateway and prevents the user/password method from being used.

There is a workaround for leaving a certificate's "common name" (cn) empty, allowing credentials to take precedence. Unfortunately, some certificate management services do not permit the creation of certificates with an empty common name.

I have prepared a PR with a slight change that makes the corresponding options configurable rather than hardcoded within the template.

https://github.com/andrewrothstein/ansible-etcd_cluster/pull/36

Kind regards,
Jk

**Comment by andrewrothstein** [comment]
I merged ur PR and published it as v3.0.8 to the galaxy. Thanks for the contribution!
