### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by varmaraju** [andrewrothstein/ansible-etcd-cluster#4]
Hi SIr,
while executing the play book, I am facing the certificate issue, could you please try to help me to fix this issue.

ASK [andrewrothstein.etcd-cluster : install keys/certs] ***********************************************************************************************************************************************
task path: /private/var/root/.ansible/roles/andrewrothstein.etcd-cluster/tasks/pki.yml:2
<192.168.33.10> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.33.10> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/private/var/root/.ansible/cp/759f2c4327 192.168.33.10 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.33.10> (0, '/root\n', '')
<192.168.33.10> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.33.10> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/private/var/root/.ansible/cp/759f2c4327 192.168.33.10 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542117524.64-240176055285189 `" && echo ansible-tmp-1542117524.64-240176055285189="` echo /root/.ansible/tmp/ansible-tmp-1542117524.64-240176055285189 `" ) && sleep 0'"'"''
<192.168.33.13> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.33.13> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/private/var/root/.ansible/cp/b269f143ae 192.168.33.13 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.33.10> (0, 'ansible-tmp-1542117524.64-240176055285189=/root/.ansible/tmp/ansible-tmp-1542117524.64-240176055285189\n', '')
<192.168.33.13> (0, '/root\n', '')
<192.168.33.13> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.33.13> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/private/var/root/.ansible/cp/b269f143ae 192.168.33.13 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542117524.67-175064468080935 `" && echo ansible-tmp-1542117524.67-175064468080935="` echo /root/.ansible/tmp/ansible-tmp-1542117524.67-175064468080935 `" ) && sleep 0'"'"''
The full traceback is:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/plugins/action/copy.py", line 457, in run
    source = self._find_needle('files', source)
  File "/Library/Python/2.7/site-packages/ansible/plugins/action/__init__.py", line 1051, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 322, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
AnsibleFileNotFound: Could not find or access '~/pki-dir/192.168.33.10-key.pem' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

failed: [192.168.33.10] (item={u'm': u'0400', u'd': u'/var/lib/etcd/test-cluster-name.pki/192.168.33.10-key.pem', u'f': u'~/pki-dir/192.168.33.10-key.pem'}) => {
    "changed": false, 
    "invocation": {
        "dest": "/var/lib/etcd/test-cluster-name.pki/192.168.33.10-key.pem", 
        "group": "etcd", 
        "mode": "0400", 
        "owner": "etcd", 
        "src": "~/pki-dir/192.168.33.10-key.pem"
    }, 
    "item": {
        "d": "/var/lib/etcd/test-cluster-name.pki/192.168.33.10-key.pem", 
        "f": "~/pki-dir/192.168.33.10-key.pem", 
        "m": "0400"
    }, 
    "msg": "Could not find or access '~/pki-dir/192.168.33.10-key.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}

**Comment by patsevanton** [comment]
Same issue on CentOS 7

```
Could not find or access '~/pki-dir/patroni1-key.pem' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

**Comment by andrewrothstein** [comment]
The role is meant to install the certs and keys for the members of the cluster. How/where are you managing the PKI that secures the communication between the processes that constitute your etcd cluster?

**Comment by patsevanton** [comment]
Hello!
I dont manage PKI.
Playbook can create new certificate when run playbook ?

**Comment by andrewrothstein** [comment]
if u don't want to secure your install then use
```yml
- role: andrewrothstein.etcd-cluster
  etcd_secure: False
```
